title: Giorgia Zaccaria

author: Research Fellow
description: > # this means to ignore newlines until "show_excerpts:"
  Thank you for visiting my webpage! 
  If you are interested in my research, please feel free to contact me at giorgia.zaccaria@unitelmasapienza.it.
    
theme: Minima



